name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_REPOSITORY: "pokedoku2-repository"
  IMAGE_NAME: "latest"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:


      - name: Checkout the repo
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Digital Ocean droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            # Stop running container
            docker stop ${{ env.IMAGE_NAME }} || true
            # Remove old container
            docker rm ${{ env.IMAGE_NAME }} || true
            # Pull the new image
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
            # Run the new container
            docker run -d \
              --restart always \
              --name ${{ env.IMAGE_NAME }} \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
